### ISSUE TITLE
How to integrate with Bootstrap theme

### ISSUE THREAD

**Issue by 101t** [bilalakil/bin#1]
How to integrate with Bootstrap theme css and html

**Comment by bilalakil** [comment]
Could you elaborate on your question? What do you want to use the bootstrap theme?

If it's the simplePagination then you should go to it's Git repository (https://github.com/flaviusmatis/simplePagination.js), check if someone has already asked this and then post it there if you still have to. That way other people who may be searching for that information would be more likely to find it.

**Comment by bilalakil** [comment]
Due to there being just about nothing other than simplePagination in this repository at the moment, and having not received any elaboration from you, I'll assume that you were indeed referring to simplePagination when asking for Bootstrap styling.

My remark in the previous comment covers that, so I'll close this issue for now.

**Comment by 101t** [comment]
That is :+1: 
http://esimakin.github.io/twbs-pagination/
